### ISSUE TITLE
Problems with uploading to Spark Packages

### ISSUE THREAD

**Issue by brkyvz** [saurfang/sparksql-protobuf#1]
Hi @saurfang. For some reason, your zip file is not being encoded properly in base64. Could you please send it to me so that I can debug it?

Thanks,
Burak

**Comment by saurfang** [comment]
Hey Burak:

Interesting. I have attached the zip file.  I have renamed zip to zzz due
to gmail security policy.

Thanks for reaching out!

Best,
Forest

**Comment by brkyvz** [comment]
Hi Forest, I unfortunately didn't get the attachment. Could you please try sending to brkyvz@gmail.com directly? Thank you!

Best,
Burak

**Comment by saurfang** [comment]
It now looks good. Thanks!
