### ISSUE TITLE
Protobuf 3

### ISSUE THREAD

**Issue by ebenoist** [saurfang/sparksql-protobuf#3]
How can I help make sure this project can support proto3?

**Comment by IceMan81** [comment]
It would be perfect if proto3 is supported. One issue is that the Parquet converters does not work correctly for all valid proto3 definitions.

**Comment by IceMan81** [comment]
https://issues.apache.org/jira/browse/PARQUET-665
Proto3 support has landed in Parquet.

**Comment by ebenoist** [comment]
Thats great news! Would this just be a matter of updating the dependency once mr-parquet releases the changes?

**Comment by saurfang** [comment]
happy to take PR/contribution. I wonder how one would handle protobuf 2.5 that is already shipped with Hadoop and Spark?

**Comment by IceMan81** [comment]
@saurfang That's a good question. There may not be a good way to support both protobuf 2.5 and protobuf 3.0. To use proto3 with Spark that already ships with proto 2.5, we can use shaded jars.

**Comment by IceMan81** [comment]
@saurfang Btw, does this work directly with Spark 2.0 or needs some re-work?

**Comment by ebenoist** [comment]
@IceMan81 this is exactly what we do for a number of our jobs.

```XML
<relocation>
  <pattern>com.google.protobuf.util</pattern
  <shadedPattern>shaded.com.google.protobuf.util</shadedPattern>
</relocation>
<relocation>
  <pattern>com.google.protobuf</pattern
  <shadedPattern>shaded.com.google.protobuf</shadedPattern>
</relocation>
```
