### ISSUE TITLE
[Question] Is there a release compatible with Scala 2.11 available?

### ISSUE THREAD

**Issue by anshbansal** [saurfang/sparksql-protobuf#7]
Looking at https://bintray.com/saurfang/maven/sparksql-protobuf I can see that the release is compatible to Scala 2.10. Is it hosted somewhere else also with Scala 2.11 compatibility?

**Comment by saurfang** [comment]
It would be easiest to compile yourself and publish to an internal repo if you are working in a company. I can also publish a new version. Do you need Scala 2.11 with Spark 2.x or Scala 2.11 with Spark 1.x since they are not backward compatible AFAIK?

**Comment by anshbansal** [comment]
Spark 2.x.

**Comment by saurfang** [comment]
Okay. Released 0.1.3 with Scala 2.11 and Spark 2.3. Let me know if you any trouble using it.
